// import Link from "next/link";
export const metadata = {
  title: "blog page",
  description: "Generated by create next app",
};

async function getData() {
  // const res = await services.dict.getDictEnums("CONSOLE_ROUTE");
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.
  // Recommendation: handle errors
  // return res;
}
export default async function Home({ params }: { params: { id: string } }) {
  const data = await getData();
  return (
    <main>
      <h1>Hello, blog {params.id}!</h1>
      <h1>Hello, blog {JSON.stringify(data)}!</h1>
    </main>
  );
}
