import { P5Modal } from "@/components";

// import Link from "next/link";
export const metadata = {
  title: "message page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main>
      <h1>123</h1>
      <P5Modal />
    </main>
  );
}
