// import { GLOBAL_ENUM } from "@/common/enums/enum";
// import jsCookie from "js-cookie";
// import Link from "next/link";
// export const metadata = {
//   title: 'blog page',
//   description: 'Generated by create next app',
// }
export default function Home() {
  // const fun = () => {
  //  throw new Error('error')
  // };
  return (
    <main>
      <h1>Hello, blog!</h1>
      <button type="button">按钮</button>
    </main>
  );
}
