export enum GLOBAL_ENUM {
  TOKEN_KEY = "CONSOLE_SNOOZEMO_COM_TOKEN",
  GET_ENUM_ROUTE_KEY = "CONSOLE_ROUTE",
  GET_ENUM_MENU_KEY = "CONSOLE_MENU",
  GET_ENUM_ROOT_KEY = "ROOT",
  GET_ENUM_USER_STATUS_KEY = "USER_STATUS",
  GET_ENUM_USER_ROLE_KEY = "USER_ROLE",
  GET_ENUM_ARTICLE_LABEL_KEY = "ARTICLE_LABEL",
}
